//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_cyrs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_cursContainer : DbContext
    {
        public BD_cursContainer()
            : base("name=BD_cursContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> EmployeesSet { get; set; }
        public virtual DbSet<Seniority> SenioritySet { get; set; }
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<Departments> DepartmentsSet { get; set; }
        public virtual DbSet<Position> PositionSet { get; set; }
    }
}
