//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_cyrs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seniority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seniority()
        {
            this.Wage_rate = 1D;
        }
    
        public int Id { get; set; }
        public System.DateTime Date_of_hiring { get; set; }
        public Nullable<System.DateTime> Date_of_dismissal { get; set; }
        public double Wage_rate { get; set; }
        public int EmployeesId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Position Position { get; set; }
    }
}
